name: Build and Scan SharpSnake

on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:    
    runs-on: windows-latest
    name: Compile assembly
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore SharpSnake.sln

      - name: Build Solution
        run: |
          msbuild.exe SharpSnake.sln /p:platform="x64" /p:configuration="Release"

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: SharpSnake
          path: D:\a\SharpSnake\SharpSnake\SharpSnake\bin\x64\Release\SharpSnake.exe

      - name: Upload Binary To Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: D:\a\SharpSnake\SharpSnake\SharpSnake\bin\x64\Release\SharpSnake.exe
          release_name: v1.1
          asset_name: SharpSnake.exe
          tag: v1.1
          overwrite: true
          body: "Latest Release."

  scan:
    needs: build
    runs-on: ubuntu-latest
    name: AV scan
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          name: SharpSnake
          path: SharpSnake/
      - name: Virustotal Scan
        uses: crazy-max/ghaction-virustotal@v2
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ./SharpSnake/SharpSnake.exe