name: Build SharpSnake

on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build:    
    runs-on: windows-latest
    
    steps:      
      - uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Setup VSTest
        uses: darenm/Setup-VSTest@v1

      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Restore Packages
        run: nuget restore SharpSnake.sln

      - name: Build Solution
        run: |
          msbuild.exe SharpSnake.sln /p:platform="x64" /p:configuration="Release"

     -  name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with: 
          name: assets-for-download
          path: D:\a\SharpSnake\SharpSnake\SharpSnake\bin\x64\Release\