name: Clamav Scan

on:  
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  gitavscan:
    runs-on: ubuntu-latest
    name: AV scan
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Malware Scanner
        uses: dell/common-github-actions/malware-scanner@main
        with:
          directories: .
          options: -ri